### PR TITLE
please help me

### PR DESCRIPTION
**Pull request by heiditang**
Screenshot_1576087171

### CODE REVIEW

**Comment by mattnazari** [comment]
change:
const TextInput to another name like const defaultTextInput

**Comment by heiditang** [comment]
please help me on the icon part please!

**Comment by heiditang** [comment]
Screenshot_1576089285

**Comment by mattnazari** [comment]
Screen Shot 2019-12-11 at 10 43 50 AM

**Comment by mattnazari** [comment]
and in App View should be:
View style={styles.bg}

**Review by mattnazari — APPROVED** [review]

**Pull request merged**
